/*
 * generated by Xtext 2.17.1
 */
package de.libutzki.xtextextras446.ide


/**
 * Use this class to register ide components.
 */
class XtextExtras446IdeModule extends AbstractXtextExtras446IdeModule {
}
