/*
 * generated by Xtext 2.17.1
 */
package de.libutzki.xtextextras446.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class XtextExtras446ProposalProvider extends AbstractXtextExtras446ProposalProvider {
}
