/*
 * generated by Xtext 2.17.1
 */
package de.libutzki.xtextextras446


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XtextExtras446StandaloneSetup extends XtextExtras446StandaloneSetupGenerated {

	def static void doSetup() {
		new XtextExtras446StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
