/*
 * generated by Xtext 2.17.1
 */
package de.libutzki.xtextextras446


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class XtextExtras446RuntimeModule extends AbstractXtextExtras446RuntimeModule {
}
