/*
 * generated by Xtext 2.17.1
 */
package de.libutzki.xtextextras446.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class XtextExtras446UiModule extends AbstractXtextExtras446UiModule {
}
