/*
 * generated by Xtext 2.17.1
 */
package de.libutzki.xtextextras446.validation


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class XtextExtras446Validator extends AbstractXtextExtras446Validator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					XtextExtras446Package.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
}
